name: Adjust readme

on: [push, pull_request]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools_scm
    - name: Adjust readme
      run: |
        python -m setuptools_scm
        echo "test" > README.md
        python -m setuptools_scm
    - name: Build package
      run: python -m build
    - name: testme
      run: |
       ls
